apiVersion: v1
kind: Service
metadata:  
  name: my-clusterip-service
spec:
  selector:    
    app: my-app
  type: ClusterIP
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP