apiVersion: v1
kind: ReplicationController
metadata:
  name: mem-burstable
spec:
  replicas: 1
  selector:
    app: memhog
  template:
    metadata:
      name: mem-burstable
      labels:
        app: memhog
    spec:
      containers:
      - name: mem-burstable
        image: lorel/docker-stress-ng
        args: ["--class", "memory", "--sequential", "0", "--vm-hang", "0"]
        resources:
          # burstable cuz limits != requests
          limits:
            cpu: "10m"
            memory: "800Mi"
          requests:
            cpu: "10m"
            memory: "600Mi"