apiVersion: v1
kind: ReplicationController
metadata:
  name: mem-starving
spec:
  replicas: 2
  selector:
    app: memhog
  template:
    metadata:
      name: mem-starving
      labels:
        app: memhog
    spec:
      containers:
      - name: mem-starving
        image: progrium/stress
        args: ["--vm", "4"]
        resources:
          limits:
            cpu: "10m"
            memory: "100M"