apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app-v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: my-app
        version: "1.10"
    spec:
      containers: 
        - name: my-app
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - name: http
              containerPort: 8080
              